### ISSUE TITLE
Discussion on #ReportAuthorGuide/Tutorial-3-Master-Report/Master-Detail-Report-With-Nested-DataRegions

### ISSUE THREAD

**Issue by reinier-lolkema** [GrapeCity/activereportsjs-docs#1]
Hi,

Thanks for your excellent tutorials. I think on this page the **JSON Paths should be $.*** as we are not using an OData endpoint.

Cheers,
Reinier

---
#### ReportAuthorGuide/Tutorial-3-Master-Report/Master-Detail-Report-With-Nested-DataRegions

**Comment by sAbakumoff** [comment]
Hello,
Thanks for the feedback. We will rewrite this tutorial soon.
