### ISSUE TITLE
Discussion on #ReportAuthorGuide/Tutorial-3-Master-Report/Master-Detail-Report-With-Nested-DataRegions

### ISSUE THREAD

**Issue by reinier-lolkema** [GrapeCity/activereportsjs-docs#2]
The suggested expressions using = and [] did not work for me. I used curly brackets instead.

<img width="960" alt="2021-06-09" src="https://user-images.githubusercontent.com/66393594/121285622-0da63700-c922-11eb-8b4d-7e3db8436aae.png">

---
#### ReportAuthorGuide/Tutorial-3-Master-Report/Master-Detail-Report-With-Nested-DataRegions

**Comment by sAbakumoff** [comment]
Hello,
Thanks for the feedback. We will rewrite this tutorial soon.
