### ISSUE TITLE
Discussion on #GettingStarted/QuickStart/QuickStart-Vue

### ISSUE THREAD

**Issue by ghost** [GrapeCity/activereportsjs-docs#3]
I am getting build errors after installing this package

error: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

---
#### GettingStarted/QuickStart/QuickStart-Vue

**Comment by sAbakumoff** [comment]
this is not specific for activereportsjs and you can fix it by increasing the memory limit for nodejs processes

**Comment by ghost** [comment]
I have tried a lot of options available in stack-overflow and git-hub, but
I wasn't able to fix them.
We have 4gb of ram with the server and utilising all is not fixed the
issue. NODE_OTIONS=" --max-old-space-size=4096"
I made the above changes but failed to get success on "npm run prod".
My windows laptop has 8gb ram, setting environment variables and
 NODE_OTIONS=" --max-old-space-size=8192"
and then npm run prod got success.

I think you can help in this regard.


Best Regards,

*V L Sudhakar Inampudi*
Software Engineer

Skype - sudhakari.cn <https://join.skype.com/invite/UvA8g0TjxvUA>
------------------------------
Capital Numbers <https://www.capitalnumbers.com/> | Skillsz
<https://www.skillsz.com/> | ZipAlert <https://zipalert.io/>
<https://www.linkedin.com/company/capitalnumbers/mycompany/>
<https://twitter.com/_cninfotech?lang=en>
<http://www.facebook.com/CapitalNumbers>
<https://www.instagram.com/capitalnumbers_com/>
Download Fact Sheet

**Comment by sAbakumoff** [comment]
the only solution that I can offer is increasing the memory limit. we will work on decreasing the bundle size, but we can't fix it right away.

**Comment by ghost** [comment]
Thank you, the build process is going to take 18 minutes  to 25
minutes  after increasing the size. We are using 4GB RAM on our server. May
I know the bundle size?,
Hoping for the best in the near future.


Best Regards,

*V L Sudhakar Inampudi*
Software Engineer

Skype - sudhakari.cn <https://join.skype.com/invite/UvA8g0TjxvUA>
------------------------------
Capital Numbers <https://www.capitalnumbers.com/> | Skillsz
<https://www.skillsz.com/> | ZipAlert <https://zipalert.io/>
<https://www.linkedin.com/company/capitalnumbers/mycompany/>
<https://twitter.com/_cninfotech?lang=en>
<http://www.facebook.com/CapitalNumbers>
<https://www.instagram.com/capitalnumbers_com/>
Download Fact Sheet
